### ISSUE TITLE
豆瓣页面 LinkedScrollView 里面的点击事件不是很灵敏

### ISSUE THREAD

**Issue by xiaofengff** [funnywolfdadada/HollowKit#2]
我把豆瓣详情页顶部的三个按钮 （想看 在看 看过），这三个按钮加上点击事件后，发现很难点中，是不是有事件冲突呢？

**Comment by funnywolfdadada** [comment]
抱歉这么晚才回复，试了下三个按钮都是可以点的，没有事件冲突，有可能时点击范围比较小，你可以试试扩大点击范围
