### ISSUE TITLE
LinkageScrollLayout手动停止fling时会响应点击事件

### ISSUE THREAD

**Issue by sankemao** [funnywolfdadada/HollowKit#3]
我看了源码在BehavioralScrollView#dispatchTouchEvent的action_down时调用stopScroll停止滚动，但同时down事件也分发给了子View，从而会额外的让点击事件也响应了

**Comment by sankemao** [comment]
初步设想在BehavioralScrollView#onInterceptTouchEvent的action_down时，判断scroller是否在滚动，如果滚动就拦截点击事件，但是这样破坏了嵌套滑动机制。
后来从嵌套子View入手，修改recyclerView如下：
```
class MyRecyclerView @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : RecyclerView(context, attrs, defStyleAttr) {

    private fun findLinkageParent(parent: ViewParent?): LinkageScrollLayout? {
         return when (parent) {
            null -> null
            is LinkageScrollLayout -> parent
            else -> findLinkageParent(parent.parent)
        }
    }

    override fun onInterceptTouchEvent(e: MotionEvent): Boolean {
        if (e.action == MotionEvent.ACTION_DOWN) {
            val linkageScrollLayout = findLinkageParent(parent)
            if (linkageScrollLayout?.scroller?.isFinished == false) {
                linkageScrollLayout.scroller.forceFinished(true)
                return true
            }
        }
        return super.onInterceptTouchEvent(e)
    }
}
```
不知能有没通用的解决方案

**Comment by funnywolfdadada** [comment]
这里的确会分发一个down事件，然后会分发cancel，讲道理不会触发onclick的，可以描述下具体场景吗？不过这里处理的的确粗糙，暂时也没找到太好的解决方案，在项目里用着没啥问题也就没再管了

**Comment by sankemao** [comment]
就在你的项目，嵌套滚动的例子中，尝试快速滑动列表，制造fling，在fling的时候点击停掉fling，此时抬起手指，子条目onClick也会一并触发，另外豆瓣详情页中也有这个现象。

**Comment by funnywolfdadada** [comment]
> 
> 
> 就在你的项目，嵌套滚动的例子中，尝试快速滑动列表，制造fling，在fling的时候点击停掉fling，此时抬起手指，子条目onClick也会一并触发，另外豆瓣详情页中也有这个现象。

问题解决了，可以拉下最新代码。down 时停了滚动，然后后续的 down 和事件会继续传递给子 view，由于子 view 已经停止滚动了，这是的 down 和 up 会被认为是 click 事件，我这里记录了 down 时的状态，如果 down 时 view 在滚动，在 up 时就拦截 up 事件防止 click
